[theme]
base = "light"
primaryColor = "#237347"
backgroundColor = "#f5f7f2"
secondaryBackgroundColor = "#edf2e8"
textColor = "#183c2b"
font = "sans serif"

[browser]
gatherUsageStats = false

[client]
toolbarMode = "minimal"
